services:
  # 1. DATABASE: Using TimescaleDB (Optimized for time-series flight data)
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: aviation_db
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. ZOOKEEPER: Manager for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: aviation_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 3. KAFKA: The 1-Hour Live Buffer
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: aviation_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # AUTO-CLEANUP: 1 Hour Retention to save your disk space
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000

  # 4. AKHQ: Kafka Visualizer
  akhq:
    image: tchiotludo/akhq:latest
    container_name: flight_kafka_ui
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka:
              properties:
                bootstrap.servers: "kafka:29092"
    ports:
      - "8085:8080" 
    depends_on:
      - kafka

  # 5. APP: The Logic Engine
  tracker:
    build: .
    container_name: flight_logic_engine
    depends_on:
      - db
      - kafka
    env_file:
      - .env.app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    volumes:
      - ./app:/app  # Live-sync code so you can edit while it runs!
      - ./data:/data

  # 6. PGADMIN: Database GUI
  pgadmin:
    image: dpage/pgadmin4
    container_name: flight_pgadmin
    env_file:
      - .env.docker
    ports:
      - "8080:80"
    depends_on:
      - db
  

volumes:
  postgres_data:

